### ISSUE TITLE
WASM js support

### ISSUE THREAD

**Issue by Humberd** [acarlsen/kmp-flagkit#1]
Hey, thanks for creating this library.

It looks like it is missing WASM js support. Will you be able to add it?

**Comment by acarlsen** [comment]
I will try to add support in next version.

**Comment by acarlsen** [comment]
Version 1.1.0 released with Wasm support.
https://github.com/acarlsen/kmp-flagkit/releases/1.1.0

**Comment by Humberd** [comment]
Wow, that was was. Thank you!
