### ISSUE TITLE
Invalid example in README

### ISSUE THREAD

**Issue by Humberd** [acarlsen/kmp-flagkit#2]
It looks like the usage example in README is invalid

https://github.com/acarlsen/kmp-flagkit/blob/main/README.md?plain=1#L57-L60

```
Icon(
    imageVector = FlagIcons.DK,
    contentDescription = "Denmark",
)
```

It probably should be `Image`, not `Icon`.

**Comment by acarlsen** [comment]
Thanks, I have updated the example.
Icon would also work, but you would need to specify tint with Color.Unspecified for it not the be one solid color.

**Comment by Humberd** [comment]
That's correct. Thank you
